In [1]:
import pandas as pd
import os
import numpy as np
import matplotlib.pyplot as plt
from youtube_api import YouTubeDataAPI

In [2]:
YT_KEY = 'AIzaSyDeNjpxlKcwb8XE7v9UO3BY46gioPxyXss'  # replace with your actual API key
yt = YouTubeDataAPI(YT_KEY)

In [3]:
searches = yt.search(q='mr beast',
                     max_results=50)
print(searches[0])

{'video_id': 'Xj0Jtjg3lHQ', 'channel_title': 'MrBeast', 'channel_id': 'UCX6OQ3DkcsbYNE6H8uQQuVA', 'video_publish_date': 1730581200.0, 'video_title': '$1 vs $500,000 Experiences!', 'video_description': "I didn't know some of these were possible MrBeast Lab Swarms are flying off the shelves! Grab yours now at Walmart, Target, ...", 'video_category': None, 'video_thumbnail': 'https://i.ytimg.com/vi/Xj0Jtjg3lHQ/hqdefault.jpg', 'collection_date': datetime.datetime(2024, 11, 13, 13, 8, 54, 75675)}

In [4]:
df_search = pd.DataFrame(searches)
df_search.head()

,video_id,channel_title,channel_id,video_publish_date,video_title,video_description,video_category,video_thumbnail,collection_date
0,Xj0Jtjg3lHQ,MrBeast,UCX6OQ3DkcsbYNE6H8uQQuVA,1.730581e+09,"$1 vs $500,000 Experiences!",I didn't know some of these were possible MrBe...,None,https://i.ytimg.com/vi/Xj0Jtjg3lHQ/hqdefault.jpg,2024-11-13 13:08:54.075675
1,4SNThp0YiU4,MrBeast,UCX6OQ3DkcsbYNE6H8uQQuVA,1.720904e+09,"50 YouTubers Fight For $1,000,000",I can't believe how intense this video got The...,None,https://i.ytimg.com/vi/4SNThp0YiU4/hqdefault.jpg,2024-11-13 13:08:54.075734
2,snX5YyflrGw,MrBeast,UCX6OQ3DkcsbYNE6H8uQQuVA,1.727557e+09,"100 Identical Twins Fight For $250,000",I've never seen this many twins in one place b...,None,https://i.ytimg.com/vi/snX5YyflrGw/hqdefault.jpg,2024-11-13 13:08:54.075771
3,9UtcHPCEBgg,MrBeast,UCX6OQ3DkcsbYNE6H8uQQuVA,1.729379e+09,1 Subscriber = 1 Penny,,None,https://i.ytimg.com/vi/9UtcHPCEBgg/hqdefault.jpg,2024-11-13 13:08:54.075803
4,UPrkC1LdlLY,MrBeast,UCX6OQ3DkcsbYNE6H8uQQuVA,1.722719e+09,"Survive 100 Days In Nuclear Bunker, Win $500,000","This video was really fun to make, I hope you ...",None,https://i.ytimg.com/vi/UPrkC1LdlLY/hqdefault.jpg,2024-11-13 13:08:54.075834

In [5]:
df_search.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   video_id            50 non-null     object
 1   channel_title       50 non-null     object
 2   channel_id          50 non-null     object
 3   video_publish_date  50 non-null     float64
 4   video_title         50 non-null     object
 5   video_description   50 non-null     object
 6   video_category      0 non-null      object
 7   video_thumbnail     50 non-null     object
 8   collection_date     50 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(1), object(7)
memory usage: 3.6+ KB

# Actual Info for Creators
### Diamond: Mrwhoistheboss (Arun Maini), Marques Brownlee, Marques Brownlee
### Gold: Austin Evans, CNET, The Tech Chap
### Silver: This is Tech Today, Chigz Tech Reviews

# Diamond

In [6]:
# List of search queries (channel names or keywords)
search_queries = ['Mrwhoistheboss', 'Marques Brownlee', 'Arun Maini', 'Austin Evans', 'CNET', 'The Tech Chap',
                  'This is Tech Today', 'Chigz Tech Reviews']

In [7]:
# Initialize an empty DataFrame to store combined results
combined_df = pd.DataFrame()

In [8]:
# Loop through each search query
for query in search_queries:
    # Perform the search for each query
    searches = yt.search(q=query, max_results=50)
    
    # Convert search results to a temporary DataFrame
    temp_df = pd.DataFrame(searches)
    
    # Initialize lists to store additional metadata for each search result
    view_counts = []
    comment_counts = []
    like_counts = []
    dislike_counts = []
    video_description = []
    
    # Loop through each video_id in the search results to get additional metadata
    for video in searches:
        video_id = video['video_id']
        metadata = yt.get_video_metadata(video_id)
        
        # Append the specific metadata values to the respective lists
        view_counts.append(metadata.get('video_view_count'))
        comment_counts.append(metadata.get('video_comment_count'))
        like_counts.append(metadata.get('video_like_count'))
        dislike_counts.append(metadata.get('video_dislike_count'))
        video_description.append(metadata.get('video_description'))
    
    # Add the new metadata columns to the temporary DataFrame
    temp_df['video_view_count'] = view_counts
    temp_df['video_comment_count'] = comment_counts
    temp_df['video_like_count'] = like_counts
    temp_df['video_dislike_count'] = dislike_counts
    temp_df['video_description'] = video_description
    
    # Append the temporary DataFrame to the combined DataFrame
    combined_df = pd.concat([combined_df, temp_df], ignore_index=True)

In [9]:
combined_df.head()

,video_id,channel_title,channel_id,video_publish_date,video_title,video_description,video_category,video_thumbnail,collection_date,video_view_count,video_comment_count,video_like_count,video_dislike_count
0,LdlLUogNYMw,Mrwhosetheboss,UCMiJRAwDNSNzuYeN2uWa0pA,1.708899e+09,I bought the CHEAPEST Tech in India!,"India hits different, loved this video, and th...",None,https://i.ytimg.com/vi/LdlLUogNYMw/hqdefault.jpg,2024-11-13 13:08:54.627093,12325383,15892,409410,None
1,4RcThoRG46c,Mrwhosetheboss,UCMiJRAwDNSNzuYeN2uWa0pA,1.728144e+09,I tested every Celebrity Tech product!,"Celebrity tech from Ronaldo, Mbappe, Will Smit...",None,https://i.ytimg.com/vi/4RcThoRG46c/hqdefault.jpg,2024-11-13 13:08:54.627147,5651718,5870,181583,None
2,kMiy8ZywF88,Mrwhosetheboss,UCMiJRAwDNSNzuYeN2uWa0pA,1.688227e+09,I bought the most EXPENSIVE Tech on the internet.,It's always fun to treat your parents 😁\nGet a...,None,https://i.ytimg.com/vi/kMiy8ZywF88/hqdefault.jpg,2024-11-13 13:08:54.627190,15469957,10570,345765,None
3,CpCZNCm5zgw,Mrwhosetheboss,UCMiJRAwDNSNzuYeN2uWa0pA,1.725645e+09,We built the Biggest iPhone in the World.,I cannot believe we get to do this - Thank you...,None,https://i.ytimg.com/vi/CpCZNCm5zgw/hqdefault.jpg,2024-11-13 13:08:54.627228,4752568,14817,265890,None
4,mISvJhV8w-w,Mrwhosetheboss,UCMiJRAwDNSNzuYeN2uWa0pA,1.702154e+09,I bought the CRAZIEST tech in Japan,Checking out all the craziest tech in Japan wi...,None,https://i.ytimg.com/vi/mISvJhV8w-w/hqdefault.jpg,2024-11-13 13:08:54.627265,11122084,8200,250068,None

In [10]:
combined_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   video_id             400 non-null    object
 1   channel_title        400 non-null    object
 2   channel_id           400 non-null    object
 3   video_publish_date   400 non-null    float64
 4   video_title          400 non-null    object
 5   video_description    400 non-null    object
 6   video_category       0 non-null      object
 7   video_thumbnail      400 non-null    object
 8   collection_date      400 non-null    datetime64[ns]
 9   video_view_count     400 non-null    object
 10  video_comment_count  400 non-null    object
 11  video_like_count     398 non-null    object
 12  video_dislike_count  0 non-null      object
dtypes: datetime64[ns](1), float64(1), object(11)
memory usage: 40.8+ KB

# A little bit of engineering

In [11]:
# Filter combined_df to only include rows where 'video_title' contains 'review' variations
filtered_df = combined_df[combined_df['video_title'].str.contains(r'\breview\w*\b', case=False, na=False)]

In [12]:
filtered_df['channel_title'].unique()

array(['Mrwhosetheboss', 'Marques Brownlee', 'Best Buy', 'Auto Focus',
       'CNET', 'The Tech Chap', 'This is Tech Today',
       'Chigz Tech Reviews'], dtype=object)

In [13]:
# Prepend YouTube URL to each video_id
filtered_df['video_id'] = filtered_df['video_id'].apply(lambda x: f"https://www.youtube.com/watch?v={x}")

/var/folders/_m/skhgc3n53pbfz_6qdt170bs40000gp/T/ipykernel_82408/2755986844.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df['video_id'] = filtered_df['video_id'].apply(lambda x: f"https://www.youtube.com/watch?v={x}")

In [14]:
filtered_df.head()

,video_id,channel_title,channel_id,video_publish_date,video_title,video_description,video_category,video_thumbnail,collection_date,video_view_count,video_comment_count,video_like_count,video_dislike_count
5,https://www.youtube.com/watch?v=8Lb9023_D0A,Mrwhosetheboss,UCMiJRAwDNSNzuYeN2uWa0pA,1.724278e+09,Google Pixel 9 Pro Review - Redemption Time!?,Full review of the Google Pixel 9 Pro and Pro ...,None,https://i.ytimg.com/vi/8Lb9023_D0A/hqdefault.jpg,2024-11-13 13:08:54.627303,2560562,4772,92452,None
16,https://www.youtube.com/watch?v=HvoBci_GC8A,Mrwhosetheboss,UCMiJRAwDNSNzuYeN2uWa0pA,1.706384e+09,Samsung S24 Ultra Review - Goodbye iPhone?,"Full Review of the Samsung Galaxy S24 Ultra, i...",None,https://i.ytimg.com/vi/HvoBci_GC8A/hqdefault.jpg,2024-11-13 13:08:54.627698,7142838,12193,201172,None
45,https://www.youtube.com/watch?v=HgqpFKiMz-I,Mrwhosetheboss,UCMiJRAwDNSNzuYeN2uWa0pA,1.709663e+09,Nothing Phone (2a) Review - Did They Lie?,"Full Review of the Nothing Phone (2a), includi...",None,https://i.ytimg.com/vi/HgqpFKiMz-I/hqdefault.jpg,2024-11-13 13:08:54.628670,3556932,4909,121088,None
61,https://www.youtube.com/watch?v=TitZV6k8zfA,Marques Brownlee,UCBJycsmduvYEL83R_U4JriQ,1.713152e+09,The Worst Product I&#39;ve Ever Reviewed... Fo...,The Humane AI pin is... bad. Almost no one sho...,None,https://i.ytimg.com/vi/TitZV6k8zfA/hqdefault.jpg,2024-11-13 13:08:57.579980,8361809,19643,239315,None
68,https://www.youtube.com/watch?v=EGkGRs6YhoM,Marques Brownlee,UCBJycsmduvYEL83R_U4JriQ,1.724278e+09,Google Pixel 9/Pro Review: Gimmick or Good?,Pixel 9 and Pixel 9 Pro are full of AI and wra...,None,https://i.ytimg.com/vi/EGkGRs6YhoM/hqdefault.jpg,2024-11-13 13:08:57.580207,4698795,8879,145346,None

In [15]:
filtered_df.to_csv('videos_df.csv', index=False)

In [16]:
filtered_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 83 entries, 5 to 399
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   video_id             83 non-null     object
 1   channel_title        83 non-null     object
 2   channel_id           83 non-null     object
 3   video_publish_date   83 non-null     float64
 4   video_title          83 non-null     object
 5   video_description    83 non-null     object
 6   video_category       0 non-null      object
 7   video_thumbnail      83 non-null     object
 8   collection_date      83 non-null     datetime64[ns]
 9   video_view_count     83 non-null     object
 10  video_comment_count  83 non-null     object
 11  video_like_count     83 non-null     object
 12  video_dislike_count  0 non-null      object
dtypes: datetime64[ns](1), float64(1), object(11)
memory usage: 9.1+ KB